services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_APPWRITE_PUBLIC_ENDPOINT: ${VITE_APPWRITE_PUBLIC_ENDPOINT}
        VITE_APPWRITE_PROJECT_ID: ${VITE_APPWRITE_PROJECT_ID}
    ports:
      - "8088:80"  # Host:Container


