services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_APPWRITE_PUBLIC_ENDPOINT: ${VITE_APPWRITE_PUBLIC_ENDPOINT}
        VITE_APPWRITE_PROJECT_ID: ${VITE_APPWRITE_PROJECT_ID}
        VITE_APP_VERSION: ${VITE_APP_VERSION:-1.1.6.2}
        VITE_BUILD_DATE: ${VITE_BUILD_DATE}
    ports:
      - "8088:80"  # Host:Container


