services:
  frontend:
    build: 
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:5055/api
    ports:
      - "8088:80"  # Host:Container
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5055:5000"  # Host:Container
    environment:
      - DATABASE_URL=postgres://wizard:geheim@db:5432/wizard_db
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: wizard
      POSTGRES_PASSWORD: geheim
      POSTGRES_DB: wizard_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
       - "5433:5432"

volumes:
  pgdata:
